services:
    AW_leagueuser_service:
        class: AW\SimpleLeagueBundle\Services\UserService
        arguments: ["@doctrine.orm.default_entity_manager"]
    AW_club_service:
        class: AW\SimpleLeagueBundle\Services\ClubService
        arguments: ["@doctrine.orm.default_entity_manager"]
    AW_team_service:
        class: AW\SimpleLeagueBundle\Services\TeamService
        arguments: ["@doctrine.orm.default_entity_manager"]
    AW_season_service:
        class: AW\SimpleLeagueBundle\Services\SeasonService
        arguments: ["@doctrine.orm.default_entity_manager"]
    AW_match_service:
        class: AW\SimpleLeagueBundle\Services\MatchService
        arguments: ["@doctrine.orm.default_entity_manager"]
    AW_league_service:
        class: AW\SimpleLeagueBundle\Services\LeagueService
        arguments: ["@doctrine.orm.default_entity_manager"]